sut:
  image: node:4
  command: sh -c 'npm install && npm test'
  volumes:
    - .:/app
  environment:
    - CI=true
  links:
    - fiotech-bitcoin-core
    - fiotech-bitcoin-core-multi-wallet
    - fiotech-bitcoin-core-ssl
    - fiotech-bitcoin-core-username-only
  working_dir: /app

fiotech-bitcoin-core:
  image: ruimarinho/fiotech-bitcoin-core:0.17-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18443
    -rpcuser=foo
    -server
  ports:
    - 18443:18443

fiotech-bitcoin-core-multi-wallet:
  image: ruimarinho/fiotech-bitcoin-core:0.17-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -wallet=wallet1
    -wallet=wallet2
    -rpcport=18453
    -rpcuser=foo
    -server
  ports:
    - 18453:18453

fiotech-bitcoin-core-ssl:
  image: ruimarinho/fiotech-bitcoin-core:0.11-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18463
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/bitcoind/cert.pem
    -rpcsslprivatekeyfile=/etc/ssl/bitcoind/key.pem
    -rpcuser=foo
    -server
  volumes:
    - ./test/config/ssl:/etc/ssl/bitcoind
  ports:
    - 18463:18463

fiotech-bitcoin-core-username-only:
  image: ruimarinho/fiotech-bitcoin-core:0.11-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcport=18473
    -rpcuser=foo
    -server
  ports:
    - 18473:18473
